### ISSUE TITLE
Cannot commit locally

### ISSUE THREAD

**Issue by afucher** [carbon-app/carbon#1363]
**Describe the change**
I made a fork using the instruction from CONTRIBUTING.md file. When I try to make a commit locally it runs the `pre-commit` tasks, and it fails on `npm run lint` due to some missing `.env` files.

```
husky > pre-commit (node v16.3.0)
✔ Preparing...
⚠ Running tasks...
  ❯ Running tasks for *.js
    ✖ npm run lint [FAILED]
    ◼ prettier --config .prettierrc --write
  ↓ No staged files match .all-contributorsrc [SKIPPED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up...

✖ npm run lint:
error - Failed to load env from .env.production.local Error: ENOTDIR: not a directory, stat '/Users/afucher/Projects/carbon/components/Carbon.js/.env.production.local'
    at Object.statSync (node:fs:1526:3)
    at Module.loadEnvConfig (/Users/afucher/Projects/carbon/node_modules/@next/env/dist/index.js:1:4113)
    at Object.loadConfig [as default] (/Users/afucher/Projects/carbon/node_modules/next/dist/server/config.js:420:21)
    at nextLint (/Users/afucher/Projects/carbon/node_modules/next/dist/cli/next-lint.js:171:50)
    at /Users/afucher/Projects/carbon/node_modules/next/dist/bin/next:130:34 {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '/Users/afucher/Projects/carbon/components/Carbon.js/.env.production.local'
}
error - Failed to load env from .env.local Error: ENOTDIR: not a directory, stat '/Users/afucher/Projects/carbon/components/Carbon.js/.env.local'
    at Object.statSync (node:fs:1526:3)
    at Module.loadEnvConfig (/Users/afucher/Projects/carbon/node_modules/@next/env/dist/index.js:1:4113)
    at Object.loadConfig [as default] (/Users/afucher/Projects/carbon/node_modules/next/dist/server/config.js:420:21)
    at nextLint (/Users/afucher/Projects/carbon/node_modules/next/dist/cli/next-lint.js:171:50)
    at /Users/afucher/Projects/carbon/node_modules/next/dist/bin/next:130:34 {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '/Users/afucher/Projects/carbon/components/Carbon.js/.env.local'
}
error - Failed to load env from .env.production Error: ENOTDIR: not a directory, stat '/Users/afucher/Projects/carbon/components/Carbon.js/.env.production'
    at Object.statSync (node:fs:1526:3)
    at Module.loadEnvConfig (/Users/afucher/Projects/carbon/node_modules/@next/env/dist/index.js:1:4113)
    at Object.loadConfig [as default] (/Users/afucher/Projects/carbon/node_modules/next/dist/server/config.js:420:21)
    at nextLint (/Users/afucher/Projects/carbon/node_modules/next/dist/cli/next-lint.js:171:50)
    at /Users/afucher/Projects/carbon/node_modules/next/dist/bin/next:130:34 {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '/Users/afucher/Projects/carbon/components/Carbon.js/.env.production'
}
error - Failed to load env from .env Error: ENOTDIR: not a directory, stat '/Users/afucher/Projects/carbon/components/Carbon.js/.env'
    at Object.statSync (node:fs:1526:3)
    at Module.loadEnvConfig (/Users/afucher/Projects/carbon/node_modules/@next/env/dist/index.js:1:4113)
    at Object.loadConfig [as default] (/Users/afucher/Projects/carbon/node_modules/next/dist/server/config.js:420:21)
    at nextLint (/Users/afucher/Projects/carbon/node_modules/next/dist/cli/next-lint.js:171:50)
    at /Users/afucher/Projects/carbon/node_modules/next/dist/bin/next:130:34 {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '/Users/afucher/Projects/carbon/components/Carbon.js/.env'
}
> Couldn't find a `pages` directory. Please create one under the project root

> carbon@4.9.5 lint
> next lint --dir . "/Users/afucher/Projects/carbon/components/Carbon.js"

husky > pre-commit hook failed (add --no-verify to bypass)
```

**Screenshots**
If applicable, add screenshots to help explain the issue.

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: MacOS
- Browser [e.g. Chrome, Safari, Firefox]: N/A

**Comment by afucher** [comment]
I'm using the option with `--no-verify` so I can evolve in my development, but I don't know if is the best approach.

**Comment by mfix22** [comment]
If you run `touch .env` to create a `.env` file, it should work.
